version: '3'
services:
  app:
    build: .
    volumes:
    #  - ./app:/usr/src/app
    - .wwebjs_auth:/usr/src/app/.wwebjs_auth
    - .wwebjs_cache:/usr/src/app/.wwebjs_cache
    - .env:/usr/src/app/.env:ro
    ports:
      - '3000:3000'
      - '80:80'
    command: ["sh", "-c", "npm install && node app.js"]
